inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Performance:
  Exclude:
    - 'test/**/*'

AllCops:
  Exclude:
    - 'test/dummy/db/*schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - 'app/**/*'
    - 'test/**/*'
